### 1. Проверка здоровья сервисов
GET http://localhost:8080/actuator/health
Content-Type: application/json

### 2. Проверка здоровья сервисов
GET http://localhost:8081/actuator/health
Content-Type: application/json

### 3. Создание заявки на кредит (credit-application-service)
POST http://localhost:8080/api/credit-applications
Content-Type: application/json

{
  "amount": 65000,
  "term": 12,
  "income": 60000,
  "currentDebt": 20000,
  "creditRating": 600
}


### 4. Получение статуса заявки
GET http://localhost:8080/api/credit-applications/2f227158-63ea-4a9d-aee1-3092c728983e/status

### 5. Тест обработки заявки (credit-processing-service)
POST http://localhost:8081/api/credit-processing/process
Content-Type: application/json

{
  "applicationId": "2f227158-63ea-4a9d-aee1-3092c728983e",
  "amount": 650000,
  "term": 12,
  "income": 60000,
  "currentDebt": 20000,
  "creditRating": 600
}

### 6. Примеры разных сценариев кредитных заявок

#### Одобренная заявка (платеж <50% дохода)
POST http://localhost:8080/api/credit-applications
Content-Type: application/json

{
  "amount": 50000,
  "term": 12,
  "income": 30000,
  "currentDebt": 5000,
  "creditRating": 750
}

> {%
    client.global.set("approvedAppId", response.body.id);
%}

#### Отклоненная заявка (платеж >50% дохода)
POST http://localhost:8080/api/credit-applications
Content-Type: application/json

{
  "amount": 200000,
  "term": 12,
  "income": 30000,
  "currentDebt": 5000,
  "creditRating": 450
}

> {%
    client.global.set("rejectedAppId", response.body.id);
%}

#### Пограничный случай
POST http://localhost:8080/api/credit-applications
Content-Type: application/json

{
  "amount": 150000,
  "term": 36,
  "income": 60000,
  "currentDebt": 10000,
  "creditRating": 720
}

> {%
    client.global.set("borderlineAppId", response.body.id);
%}