spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: credit-processing-group

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8081