spring:
  application:
    name: credit-processing-service
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: credit-processing-group
      auto-offset-reset: earliest
      properties:
        spring.json.value.default.type: com.example.creditcommon.event.ApplicationEvent
        spring.json.trusted.packages: com.example.creditcommon
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    template:
      exchange: credit-exchange
      routing-key: credit-responses

rabbitmq:
  queue:
    credit-responses: credit-responses