spring:
  management:
    endpoint:
      health:
        enabled: true
    endpoints:
      web:
        exposure:
          include: health

  datasource:
    url: jdbc:postgresql://localhost:5432/credit_db
    username: postgres
    password: Serebro11!!
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue:
      credit-responses: credit-responses

server:
  port: 8080